// Code generated by protoc-gen-go-json. DO NOT EDIT.
// source: test.proto

package myproto

import (
	"encoding/json"
)

// MarshalJSON implements json.Marshaler
func (msg *UUID) MarshalJSON() ([]byte, error) {
	var buf [38]byte
	buf[0] = '"'
	buf[len(buf)-1] = '"'

	view := buf[1 : len(buf)-1]

	var offsets = [...]int{0, 2, 4, 6, 9, 11, 14, 16, 19, 21, 24, 26, 28, 30, 32, 34}
	const hexString = "0123456789abcdef"

	for i, b := range msg.Data {
		view[offsets[i]] = hexString[b>>4]
		view[offsets[i]+1] = hexString[b&0xF]
	}
	view[8] = '-'
	view[13] = '-'
	view[18] = '-'
	view[23] = '-'

	return buf[:], nil
}

var _ json.Marshaler = (*UUID)(nil)
